#!/bin/sh
#
# (C) 2009-2013 Mika Ilmaranta <ilmis@nullnet.fi>
#
# License: GPLv2
#

#
# default event handling script
#

STATE=${1}
NAME=${2}
CHECKIP=${3}
DEVICE=${4}
WARN_EMAIL=${5}
REPLIED=${6}
WAITING=${7}
TIMEOUT=${8}
REPLY_LATE=${9}
CONS_RCVD=${10}
CONS_WAIT=${11}
CONS_MISS=${12}
AVG_RTT=${13}
SRCIP=${14}
PREVSTATE=${15}
TIMESTAMP=${16}

DATE=$(/bin/date --date=@${TIMESTAMP})

if [ "${WARN_EMAIL}" = "-" ] ; then
    exit 0;
fi

cat <<EOM | mail -s "LSM: ${NAME} ${STATE}, IP ${CHECKIP}" ${WARN_EMAIL}

Hi,

Your connection ${NAME} has changed it's state to ${STATE} at ${DATE}.

Following parameters were passed:
prevstate    = ${PREVSTATE}
newstate     = ${STATE}
name         = ${NAME}
checkip      = ${CHECKIP}
device       = ${DEVICE}
sourceip     = ${SRCIP}
warn_email   = ${WARN_EMAIL}

Packet statuses:
replied      = ${REPLIED} packets replied
waiting      = ${WAITING} packets waiting for reply
timeout      = ${TIMEOUT} packets that have timed out (= packet loss)
reply_late   = ${REPLY_LATE} packets that received a reply after timeout
cons_rcvd    = ${CONS_RCVD} consecutively received replies in sequence
cons_wait    = ${CONS_WAIT} consecutive packets waiting for reply
cons_miss    = ${CONS_MISS} consecutive packets that have timed out
avg_rtt      = ${AVG_RTT} average rtt [usec], calculated from received packets

BR,
Your LSM installation

EOM

exit 0;

#EOF
